-- Tabla PROVINCIA
CREATE TABLE provincia (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  codigo31662 CHAR(4) UNIQUE NOT NULL
);

-- Tabla LOCALIDAD
CREATE TABLE localidad (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  provincia_id SMALLINT NOT NULL REFERENCES provincia(id) ON DELETE RESTRICT,
  nombre VARCHAR(50) NOT NULL,
  codigopostal SMALLINT NOT NULL
);

-- Tabla DIRECCION
CREATE TABLE direcciones (
  direccion_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tipo TEXT CHECK (
    tipo IN (
      'CLIENTE',
      'ALMACEN',
      'PROVEEDOR',
      'REPARTIDOR',
      'PUNTO_RETIRO'
    )
  ) NOT NULL,
  calle VARCHAR(200) NOT NULL,
  numero INTEGER NOT NULL,
  departamento VARCHAR(50),
  localidad_id INTEGER NOT NULL REFERENCES localidad(id) ON DELETE RESTRICT,
  activa BOOLEAN NOT NULL DEFAULT TRUE
);