INSERT INTO provincia (nombre, codigo31662)
VALUES
  ('Ciudad Autónoma de Buenos Aires (CABA)', 'AR-C'),
  ('Buenos Aires', 'AR-B'),
  ('Catamarca', 'AR-K'),
  ('Córdoba', 'AR-X'),
  ('Corrientes', 'AR-W'),
  ('Entre Ríos', 'AR-E'),
  ('Jujuy', 'AR-Y'),
  ('Mendoza', 'AR-M'),
  ('La Rioja', 'AR-F'),
  ('Salta', 'AR-A'),
  ('San Juan', 'AR-J'),
  ('San Luis', 'AR-D'),
  ('Santa Fe', 'AR-S'),
  ('Santiago del Estero', 'AR-G'),
  ('Tucumán', 'AR-T'),
  ('Chaco', 'AR-H'),
  ('Chubut', 'AR-U'),
  ('Formosa', 'AR-P'),
  ('Misiones', 'AR-N'),
  ('Neuquén', 'AR-Q'),
  ('La Pampa', 'AR-L'),
  ('Río Negro', 'AR-R'),
  ('Santa Cruz', 'AR-Z'),
  ('Tierra del Fuego', 'AR-V');