#!/bin/sh
if [ "$(git rev-parse --abbrev-ref HEAD)" = "develop" ]; then
  npx standard-version --release-as patch --skip.tag --skip.commit
  git add CHANGELOG.md package.json package-lock.json
  git commit --amend --no-edit --no-verify
fi