name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run release:prod
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): bump version to 0.x.0"
          file_pattern: CHANGELOG.md package.json package-lock.json
      - run: git push --tags